server:
  port: 8080

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123"      
  dbname: "hmdp"
  max_idle_conns: 10   
  max_open_conns: 10   

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123321"  
  db: 0
  max_active: 10 
  max_idle: 10